### ISSUE TITLE
Не работает с отчеством более 10 символов

### ISSUE THREAD

**Issue by sadstone** [IDQDD/qrmosru#4]
При попытке передать число 10 или выше как длину отчества - учитывает только первый символ, то есть 1.

**Comment by IDQDD** [comment]
вот эта да
первое ssue на гитхабе
спасибо тебе!!

ну а что по теме то да признаю сделано на отыбись
количество звездочек кодируется одним символом

впринципе могу сделать любую базу вместо десятичной
например 16-ричную
тогда цифры продолжат играть роль цифр, а далее такое соответствие:

a - 10 
b - 11
c - 12
d - 13
e - 14
f - 15

пойдет?

**Comment by Toliak** [comment]
Может прикрутить регулярку для парса?👉👈🤔

**Comment by AntonBorisovRu** [comment]
> впринципе могу сделать любую базу вместо десятичной
> например 16-ричную
> тогда цифры продолжат играть роль цифр, а далее такое соответствие

мне кажется, 16-ричной должно быть более чем достаточно.
